#!/usr/bin/env bash
# testo2c setup script
#
# Usage:
#   bash setup.sh [HOSTNAME]
#
# HOSTNAME  The hostname or IP Caddy should bind to and include in its TLS
#           certificate SAN.  Defaults to "localhost".
#
# Examples:
#   bash setup.sh                     # local machine (localhost)
#   bash setup.sh 192.168.1.42        # LAN IP
#   bash setup.sh testo2c.example.com # domain name
#
# After running, the cluster is up and accessible at:
#   https://<HOSTNAME>:35581/app/    node 1
#   https://<HOSTNAME>:35582/app/    node 2
#   https://<HOSTNAME>:35583/app/    node 3
#   https://<HOSTNAME>:35591/sim/status   sim-agent-1 control
#   https://<HOSTNAME>:35592/sim/status   sim-agent-2 control
#   https://<HOSTNAME>:35593/sim/status   sim-agent-3 control
#
# TLS uses Caddy's built-in local CA.  On Linux the CA is installed into the
# system trust store automatically.  On other systems run once after startup:
#   docker compose exec caddy caddy trust

set -euo pipefail

HOSTNAME="${1:-localhost}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== testo2c setup ==="
echo "Hostname : ${HOSTNAME}"
echo "Ports    : 35581-35583 (nodes), 35591-35593 (sim agents)"
echo

# Write Caddyfile with the given hostname.
cat > "${SCRIPT_DIR}/Caddyfile" <<EOF
# testo2c — Caddy TLS reverse proxy
# Generated by setup.sh for hostname: ${HOSTNAME}
#
# Port map:
#   35581 → orbital-node1
#   35582 → orbital-node2
#   35583 → orbital-node3
#   35591 → sim-agent-1
#   35592 → sim-agent-2
#   35593 → sim-agent-3

{
    admin off
}

${HOSTNAME}:35581 {
    tls internal
    reverse_proxy orbital-node1:8080
}

${HOSTNAME}:35582 {
    tls internal
    reverse_proxy orbital-node2:8080
}

${HOSTNAME}:35583 {
    tls internal
    reverse_proxy orbital-node3:8080
}

${HOSTNAME}:35591 {
    tls internal
    reverse_proxy sim-agent-1:9200
}

${HOSTNAME}:35592 {
    tls internal
    reverse_proxy sim-agent-2:9200
}

${HOSTNAME}:35593 {
    tls internal
    reverse_proxy sim-agent-3:9200
}
EOF

echo "Caddyfile written."

# Start (or recreate) the cluster.
cd "${SCRIPT_DIR}"
docker compose down --remove-orphans 2>/dev/null || true
docker compose up -d

echo
echo "Waiting for cluster to become healthy..."
# Poll node 1 until it responds (up to 60 s).
for i in $(seq 1 30); do
    if curl -sk "https://${HOSTNAME}:35581/healthz" | grep -q ok 2>/dev/null; then
        break
    fi
    sleep 2
done

echo
echo "=== Cluster ready ==="
echo "  Node 1 : https://${HOSTNAME}:35581/app/"
echo "  Node 2 : https://${HOSTNAME}:35582/app/"
echo "  Node 3 : https://${HOSTNAME}:35583/app/"
echo "  Sim  1 : https://${HOSTNAME}:35591/sim/status"
echo "  Sim  2 : https://${HOSTNAME}:35592/sim/status"
echo "  Sim  3 : https://${HOSTNAME}:35593/sim/status"
echo
echo "If your browser shows a TLS warning, run once:"
echo "  docker compose exec caddy caddy trust"
