#!/usr/bin/env bash
# testo2c setup script
#
# Usage:
#   bash setup.sh [HOSTNAME]
#
# HOSTNAME  The hostname or IP Caddy should bind to and include in its TLS
#           certificate SAN.  Defaults to "localhost".
#
# Examples:
#   bash setup.sh                     # local machine (localhost)
#   bash setup.sh 192.168.1.42        # LAN IP
#   bash setup.sh testo2c.example.com # domain name
#
# After running, the cluster is up and accessible at:
#   https://<HOSTNAME>:35581/app/    node 1
#   https://<HOSTNAME>:35582/app/    node 2
#   https://<HOSTNAME>:35583/app/    node 3
#   https://<HOSTNAME>:35591/sim/status   sim-agent-1 control
#   https://<HOSTNAME>:35592/sim/status   sim-agent-2 control
#   https://<HOSTNAME>:35593/sim/status   sim-agent-3 control
#
# TLS uses Caddy's built-in local CA.  This script installs the CA cert into
# the system trust store (Chrome/Chromium pick it up automatically).
# Firefox requires a one-time manual import — instructions are printed below.

set -euo pipefail

HOSTNAME="${1:-localhost}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CA_CERT_PATH="/tmp/caddy-testo2c-root.crt"

echo "=== testo2c setup ==="
echo "Hostname : ${HOSTNAME}"
echo "Ports    : 35581-35583 (nodes), 35591-35593 (sim agents)"
echo

# ── 1. Write Caddyfile ────────────────────────────────────────────────────────
cat > "${SCRIPT_DIR}/Caddyfile" <<EOF
# testo2c — Caddy TLS reverse proxy
# Generated by setup.sh for hostname: ${HOSTNAME}
#
# Port map:
#   35581 → orbital-node1
#   35582 → orbital-node2
#   35583 → orbital-node3
#   35591 → sim-agent-1
#   35592 → sim-agent-2
#   35593 → sim-agent-3

{
    admin off
}

${HOSTNAME}:35581 {
    tls internal
    reverse_proxy orbital-node1:8080
}

${HOSTNAME}:35582 {
    tls internal
    reverse_proxy orbital-node2:8080
}

${HOSTNAME}:35583 {
    tls internal
    reverse_proxy orbital-node3:8080
}

${HOSTNAME}:35591 {
    tls internal
    reverse_proxy sim-agent-1:9200
}

${HOSTNAME}:35592 {
    tls internal
    reverse_proxy sim-agent-2:9200
}

${HOSTNAME}:35593 {
    tls internal
    reverse_proxy sim-agent-3:9200
}
EOF

echo "Caddyfile written."

# ── 2. Start the cluster ──────────────────────────────────────────────────────
cd "${SCRIPT_DIR}"
docker compose down --remove-orphans 2>/dev/null || true
docker compose up -d

echo
echo "Waiting for Caddy to generate its CA and for node 1 to become healthy..."
for i in $(seq 1 30); do
    if curl -sk "https://${HOSTNAME}:35581/healthz" 2>/dev/null | grep -q ok; then
        break
    fi
    sleep 2
done

# ── 3. Install the Caddy CA certificate into the host trust store ─────────────
echo
echo "Extracting Caddy CA certificate..."
docker compose exec caddy \
    cat /data/caddy/pki/authorities/local/root.crt > "${CA_CERT_PATH}"

TRUSTED=false

# Debian / Ubuntu / Linux Mint
if command -v update-ca-certificates &>/dev/null; then
    echo "Installing CA cert into system trust store (Debian/Ubuntu)..."
    sudo cp "${CA_CERT_PATH}" /usr/local/share/ca-certificates/caddy-testo2c.crt
    sudo update-ca-certificates
    TRUSTED=true
# Fedora / RHEL / CentOS
elif command -v update-ca-trust &>/dev/null; then
    echo "Installing CA cert into system trust store (Fedora/RHEL)..."
    sudo cp "${CA_CERT_PATH}" /etc/pki/ca-trust/source/anchors/caddy-testo2c.crt
    sudo update-ca-trust extract
    TRUSTED=true
# macOS
elif command -v security &>/dev/null; then
    echo "Installing CA cert into macOS keychain..."
    sudo security add-trusted-cert -d -r trustRoot \
        -k /Library/Keychains/System.keychain "${CA_CERT_PATH}"
    TRUSTED=true
fi

# Chrome / Chromium on Linux: also add to the NSS shared DB so
# Chromium-based browsers pick it up even without a restart.
if command -v certutil &>/dev/null; then
    for NSSDB in $(find "${HOME}" \
            \( -name "cert9.db" -o -name "cert8.db" \) \
            -not -path "*/Trash/*" 2>/dev/null \
        | xargs -I{} dirname {}); do
        certutil -A -n "Caddy testo2c local CA" \
            -t "CT,," -i "${CA_CERT_PATH}" -d "${NSSDB}" 2>/dev/null && \
            echo "  Added to NSS store: ${NSSDB}" || true
    done
fi

# ── 4. Print result ───────────────────────────────────────────────────────────
echo
echo "=== Cluster ready ==="
echo "  Node 1 : https://${HOSTNAME}:35581/app/"
echo "  Node 2 : https://${HOSTNAME}:35582/app/"
echo "  Node 3 : https://${HOSTNAME}:35583/app/"
echo "  Sim  1 : https://${HOSTNAME}:35591/sim/status"
echo "  Sim  2 : https://${HOSTNAME}:35592/sim/status"
echo "  Sim  3 : https://${HOSTNAME}:35593/sim/status"
echo

if $TRUSTED; then
    echo "CA certificate installed — Chrome/Chromium should trust the site now."
    echo "(Restart the browser if it was already open.)"
else
    echo "Could not auto-install CA cert.  Import manually:"
    echo "  ${CA_CERT_PATH}"
fi

echo
echo "Firefox requires a one-time manual import:"
echo "  Settings → Privacy & Security → View Certificates"
echo "  → Authorities tab → Import → ${CA_CERT_PATH}"
echo "  Check: 'Trust this CA to identify websites'"
